### PR TITLE
Change URL to rawgithub for the pull

### PR DESCRIPTION
**Pull request by jtenner**
Alright! Here it is!

World's smallest fix.  Seriously.

### CODE REVIEW

**Comment by jgallen23** [comment]
thanks

**Comment by jtenner** [comment]
Thank YOU!  Now will these changes be reflected in the NPM module?  (I don't know how the ecosystem works)

**Comment by jgallen23** [comment]
I published 0.5.1

**Comment by jtenner** [comment]
It still spits out a 404 message now.

**Comment by jtenner** [comment]
My fault :(.

**Pull request merged**
