### PR TITLE
Add version 1.11.1 and 2.1.x

### PR DESCRIPTION
**Pull request by peterkinmond**
Added jQuery version 1.11.1, 2.1.0, and 2.1.1. Deliberately didn't bump the jQuery submodule version since it checks out to the correct tag number anyway. This includes both the latest versions for both jQuery 1.x and 2.x. The default version is still set to 1.x.

### CODE REVIEW

**Comment by jgallen23** [comment]
thanks @peterkinmond! Any interest in getting added as a collaborator on the project?

**Comment by peterkinmond** [comment]
@jgallen23 yeah that'd be great. happy to help out some more with this project. it was a big help when we scoped down our library's use of jQuery.

**Comment by peterkinmond** [comment]
@jgallen23 yeah that'd be great

**Comment by peterkinmond** [comment]
Sorry meant to just comment not comment and close

**Pull request merged**
